/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javagamechapter6;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author hardnett
 */
public class ImageTestsMain extends javax.swing.JFrame {

    /**
     * Creates new form ImageTestsMain
     */
    public ImageTestsMain() {
        initComponents();
        
        ImagesTests ttPanel = new ImagesTests();
        this.getContentPane().add(ttPanel, BorderLayout.CENTER);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        
        this.setResizable(false);
    }

    // these methods are added to get the game started when the screen is launched.
    // Thsi must be done for all examples.
    public void windowActivated(java.awt.event.WindowEvent e) {
        ((ImagesTests)imagesTestPanel).resumeGame();
    }
    
    public void windowDeactivated(java.awt.event.WindowEvent e) {
        ((ImagesTests)imagesTestPanel).pauseGame();
    }
    
    public void windowDeiconified(java.awt.event.WindowEvent e) {
        ((ImagesTests)imagesTestPanel).resumeGame();
    }
    
    public void windowIconified(java.awt.event.WindowEvent e) {
        ((ImagesTests)imagesTestPanel).pauseGame();
    }
    
    public void windowClosing(java.awt.event.WindowEvent e) {
        ((ImagesTests)imagesTestPanel).stopGame();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagesTestPanel = new ImagesTests();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imagesTestPanelLayout = new javax.swing.GroupLayout(imagesTestPanel);
        imagesTestPanel.setLayout(imagesTestPanelLayout);
        imagesTestPanelLayout.setHorizontalGroup(
            imagesTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        imagesTestPanelLayout.setVerticalGroup(
            imagesTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagesTestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagesTestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageTestsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageTestsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageTestsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageTestsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         // switch on the translucency acceleration in windows
        System.setProperty("sun.java2d.transaccel", "true");
        System.setProperty("sun.java2d.ddforcevram", "true");
        
        // use hardware acceleration using pbuffers for OpenGL
        System.setProperty("sun.java2d.opengl", "true");
        
      
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageTestsMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagesTestPanel;
    // End of variables declaration//GEN-END:variables
}
